export const CREATE_SCRATCHPAD = 'CREATE_SCRATCHPAD';
export const DELETE_SCRATCHPAD = 'DELETE_SCRATCHPAD';
export const EDIT_SCRATCHPAD = 'EDIT_SCRATCHPAD';

export const CREATE_NOTE_GROUP = 'CREATE_NOTE_GROUP';
export const DELETE_NOTE_GROUP = 'DELETE_NOTE_GROUP';
export const EDIT_NOTE_GROUP_NAME = 'EDIT_NOTE_GROUP_NAME';
export const EDIT_NOTE_GROUP_COLOR = 'EDIT_NOTE_GROUP_COLOR';
export const CREATE_NOTE = 'CREATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
